[project]
name = "am-mix"
version = "0.0.1"
readme = "README.md"
description = "My first application"

requires-python = ">=3.10"

dependencies = [
    "aiojobs>=1.4.0",
    "gamdl==3.6",
    "pyloid",
    "pyyaml",
]

[dependency-groups]
dev = [
    "pyloid-builder",
    "pyloid-watcher",
    "ruff",
]
